name: dnsc
description: A lightweight DNS checker CLI tool.
version: 0.1.0
repository: https://github.com/riccardo-tralli/dnsc

environment:
    sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
    args: ^2.7.0
    dnsolve:
        path: ../dnsolve

dev_dependencies:
    lints: ^6.0.0
    test: ^1.25.6
